export const APP_WRITE_ID = 'srm-database'
export const DB_ID = 'srm-base'
export const COLLECTION_DEALS = 'deals'
export const COLLECTION_CUSTOMERS = 'customers'
export const COLLECTION_COMMENTS = 'comments'
export const STORAGE_ID = 'storage'
